// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYUgVIu4eJtmo88ABXcF4Rlf287bvQMg',
    appId: '1:811625592959:web:f627fa8ea6f06afad2a74a',
    messagingSenderId: '811625592959',
    projectId: 'food-delivery-app-74dd4',
    authDomain: 'food-delivery-app-74dd4.firebaseapp.com',
    databaseURL: 'https://food-delivery-app-74dd4-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-74dd4.appspot.com',
    measurementId: 'G-80Q9N7071V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQhsryqULFE8C7rYmc_nG2S1UspcvcX4',
    appId: '1:811625592959:android:a4f9c702b6bfd689d2a74a',
    messagingSenderId: '811625592959',
    projectId: 'food-delivery-app-74dd4',
    databaseURL: 'https://food-delivery-app-74dd4-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-74dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEe24iYXHmBQA4j0zpBlkmFLMrJfz6lA',
    appId: '1:811625592959:ios:91f74f827d325a28d2a74a',
    messagingSenderId: '811625592959',
    projectId: 'food-delivery-app-74dd4',
    databaseURL: 'https://food-delivery-app-74dd4-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-74dd4.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRYUgVIu4eJtmo88ABXcF4Rlf287bvQMg',
    appId: '1:811625592959:web:4352b42ce23c4bd5d2a74a',
    messagingSenderId: '811625592959',
    projectId: 'food-delivery-app-74dd4',
    authDomain: 'food-delivery-app-74dd4.firebaseapp.com',
    databaseURL: 'https://food-delivery-app-74dd4-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-app-74dd4.appspot.com',
    measurementId: 'G-ZP390RS27P',
  );
}
